### PR TITLE
Updated CI configuration to use default settings

### PR DESCRIPTION
**Pull request by olleolleolle**
## Overview

To not have to update the `rvm` marker for a new ruby, this PR makes the Travis build script find the .ruby-version instead.

## Details

It also drops the custom (same) task for `script`. bundle exec rake is default for ruby builds.

  - drop the `rvm` marker (use the .ruby-version for this)
  - drop the `script` (use the default, which is the same as before)

### CODE REVIEW

**Comment by bkuhlmann** [comment]
This is excellent, thanks! I'll be applying this update to the rest of my projects next so they can benefit from this change as well.

Would you mind making a slight change to your Git commit so that it is prefixed with "Updated"?Example: "Updates Travis CI configuration to rely on default settings." This'll help conform to my auto-generated release notes ([example](https://github.com/bkuhlmann/tocer/releases/tag/v3.1.0)) when I push out the next version.

**Comment by olleolleolle** [comment]
👌- and done. 

I had the settings set to Allow Maintainer Edits.

**Comment by bkuhlmann** [comment]
Oh, sorry, I meant the commit message itself not the PR title. I'm OK with the PR title but the Git history is more important to me. You can easily fix the Git label by doing the following:

```
git rebase --interactive @~1
<within your editor, change "pick" to "r" and then save -- you'll then be shown your original message which you can rename>
git push --force-with-lease
```

That should do it. 😄

**Comment by olleolleolle** [comment]
Oh, a guess: would it do for you to make the Squash Commit green button press and reauthor the message?

**Comment by bkuhlmann** [comment]
Actually, I checked out your fork and reworded the commit message. *IMPORTANT: You'll have to delete your feature branch and recheck it out...but that won't matter much once I merge this.*

I'll end up as a co-author on the commit but you should still get attribution. :)

Thanks for doing this work, I'm happy to get this checked in.

**Comment by olleolleolle** [comment]
Thanks! I was away from the command prompt. Glad you could use it.

**Pull request merged**
