### PR TITLE
use of wildcard splat requires value to be inclosed in quotes

### PR DESCRIPTION
**Pull request by MadBomber**

### CODE REVIEW

**Comment by bkuhlmann** [comment]
Closing due to lack of feedback.

**Comment by MadBomber** [comment]
when I attempted to use `tocer` with a config file as described in the README.md file all I would get is a stack trace point to the splat as an invalid character.  Adding the quotes solved that problem.  I'm running  MRI v2.5.1 on a MacOS 10.13.4

**Comment by bkuhlmann** [comment]
OK, I see what you mean. I can see how that'd be confusing. Would you mind explaining these details in the PR template and Git commit? If you run `bundle exec rake` locally on your feature branch, you'll see the build warnings that need to be fixed. I'd also suggest that all array items be encased in quotes in order to be consistent. When fixing up the commit use rebase and/or amend on the single commit. Thanks!

**Comment by bkuhlmann** [comment]
Closing due to lack of feedback. Will incorporate changes (would have liked to have given credit, though).

**Pull request closed without merging**
